### PR TITLE
Fast Builtin Sorting

### LINKED ISSUE #6293: `roc test` segfaults on `List.sortWith`
# system
- Roc version `github:roc-lang/roc/dc37b7a31d4fa2014ec159eda1d51c27832ddca6`
- run on macOS 13.4.1 arm64 (M1 macbook air)

# setup
main.roc
```coffee
# references
# - https://github.com/roc-lang/examples/tree/main/examples/CommandLineArgs
app "main"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
    }
    imports [pf.Stdout, pf.Task]
    provides [main] to pf

main : Task.Task {} I32
main =
    Stdout.line "w/e"

expect
    n = 29792
    list = List.range { start: At n, end: Before 0 }
    List.sortWith list Num.compare == List.range { start: At 1, end: At n }
```

# problem
Running `roc test` terminates with the message:

```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
zsh: abort      roc test
```

# expected behavior
The program should not segfault.

# debugging

- the critical value at which the segfault occurs on my machine seems to be `29792`. Replacing this with `n = 29791` makes the test run without error as expected.
- using the `--optimize` flag changes the critical value. `roc test --optimize` will segfault with `n = 86898` and pass with `n = 86897`.

### LINKED ISSUE #6294: `List.sortWith` is notably slower than sorting in other non-systems languages
# system
- Roc version `github:roc-lang/roc/dc37b7a31d4fa2014ec159eda1d51c27832ddca6`
- run on macOS 13.4.1 arm64 (M1 macbook air)

# setup
main.roc
```coffee
# references
# - https://github.com/roc-lang/examples/tree/main/examples/CommandLineArgs
app "main"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
    }
    imports [pf.Stdout, pf.Task]
    provides [main] to pf

main : Task.Task {} I32
main =
    Stdout.line "w/e"

expect
    n = 86896
    list = List.range { start: At n, end: Before 0 }
    List.sortWith list Num.compare == List.range { start: At 1, end: At n }
```

# problem
Running `roc test --optimize` terminates **after ~20 seconds** with the following correct test output:

```
$ roc test --optimize

0 failed and 1 passed in 20094 ms.

```

# expected behavior
The given code should run faster relative to other languages, as [described on the Roc website](https://github.com/roc-lang/roc/blob/1d1f9a376983623e54a43cebb39c8c732bc721e5/www/content/fast.md#generally-faster-than-dynamic-or-gradual-languages-faster-than).

Specifically, I consider the above code to be roughly equivalent to the following Python code:

```py3
n = 10000000 # a much larger value!
l = list(reversed(range(n)))
l.sort()
l == list(range(n))
```

Timing this code via the *nix `time` command produces the following output:
```sh
$ time python3 -c "n = 10000000; l = list(reversed(range(n))); l.sort(); l == list(range(n))"
python3 -c   0.36s user 0.10s system 96% cpu 0.475 total
```

Note that the above results are for a data input ~300x larger than in the Roc code. (Atm the roc code won't even run for data that large - see #6293.)

### PR DESCRIPTION
**Pull request by bhansconnect**
Switch sorting over to [fluxsort](https://github.com/scandum/fluxsort). This is a modern and super fast sorting algorithm ([perf info here](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/faster.20sorting/near/454705605)). 
As part of the change, end up generating 4 specialization of sorting based on whether or not the closure is refcount and whether the element size is so large that it is smarter to sort a list of pointers rather than sorting the actual list.

I am pretty confident in the implementation cause I have run a solid amount of fuzzing.

fixes #6293
fixes #6294

### CODE REVIEW

**Comment by bhansconnect** [comment]
Cool, all tests are passing first try.

File: crates/compiler/builtins/bitcode/src/fuzz_sort.zig [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+extern fn free(c_ptr: *anyopaque) callconv(.C) void;
+
+fn cMain() callconv(.C) i32 {
+    fuzz_main() catch unreachable;
+    return 0;
+}
+
+comptime {
+    @export(cMain, .{ .name = "main", .linkage = .Strong });
+}
```
Comment (lukewilliamboswell) [inline crates/compiler/builtins/bitcode/src/fuzz_sort.zig:14]: Why do we do this? I'm guessing it's to force zig to keep the `main` symbol in the static library.

**Review by rtfeldman — APPROVED** [review]
Love it!!! Thanks so much for this @bhansconnect! 😻 😻 😻

File: crates/compiler/builtins/bitcode/src/fuzz_sort.zig (hunk 1 above)
Comment (bhansconnect) [reply crates/compiler/builtins/bitcode/src/fuzz_sort.zig:14]: Exactly that. And we have to build a static library cause Zig doesn't have the capability to generate an executable for fuzzing. Instead, we generate a static library and have c++ deal with instrumentation of the llvm ir and final linking
