### PR TITLE
Implement fixpoint-fixing and unconditionally emplace variables into type indices

### LINKED ISSUE #4077: stack overflow / bus error if there's an alias reference to a mutually recursive type
If you have this file:

```elixir
platform "roc-lang/rbt"
    requires {} { init : Job }
    exposes []
    packages {}
    imports []
    provides [initForHost]

initForHost : Job
initForHost = init

Input : [FromProjectSource, FromJob Job]

Job : [Job { inputs : List Input }]

job : { inputs : List Input } -> Job
job = \config -> Job config
```

On running `roc check`, you'll get a stack overflow or a bus error (depending on build type.)

If you remove the `Job` member of the `FromJob` tag, or the type annotation for `job`, the error goes away. I guess `FromProjectSource` is not strictly required either (the error still happens without it) but I did all my testing with that in place so into the bug report it goes!

This is true as of da75f55aeacc18b452d3e359557599e1c1eca006, but I tested back to 3a12aa26ccb347a2374c01e960d37f77b8b3b8b0 and the bug is present.

### PR DESCRIPTION
**Pull request by ayazhafiz**
This supersedes #4121 as a "better" implementation of fixpoint fixing and related constraint bug fixes, the latter of which is now not necessary due to variable emplacement of types/Types SoA. Includes:

- Implementation of fixpoint-fixing, as described in https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/alias.20references.20to.20mutually.20recursive.20types. See also the new file `unify/src/fix.rs` for a description of the procedure and why we do it.

- [Correct emplace variables in type indices during translation](https://github.com/roc-lang/roc/commit/8cf896f03afdf09ca6ef603b6ccf384050f5df34) 
Prior to this commit, we emplaced type variables into `Index<TypeTag>`
only for translated top-level types. However, we need to be careful to
do this emplacement for nested types as well! This patch ensures we do,
but immediately emplacing the destination variable of a type when we
allocate a variable for it.

- Turning off building and running `args.roc` for now.
  Args.roc has always been in a broken state, relying on particular
hand-holding of the compiler to operate. With recent changes to type
emplacement, Args.roc now shows off compiler bugs that cannot be papered
over and need to be addressed head-on. These are problems that I do not
think can be directly solved via eliminating type emplacement; I think
they are a combination of constraining and mono bugs, and will be
investigated separately.

  For now, turn off attempts to build Args, and instead just test that
`roc check` continues to behave well.

The next step will be to investigate what's still going wrong in Args.roc,
and other examples like Brian Carrol's virtual DOM, the effect interpreter,
rbt, and others.

Closes #4077

### CODE REVIEW

File: crates/compiler/test_gen/src/gen_primitives.rs [hunk 1]
```diff
@@ -2513,7 +2513,7 @@ fn function_malformed_pattern() {
 
 #[test]
 #[cfg(any(feature = "gen-llvm", feature = "gen-wasm"))]
-#[should_panic(expected = "Hit an erroneous type when creating a layout for")]
+#[ignore = "causes alias analysis panics, should roc_panic"]
```
Comment (folkertdev) [inline crates/compiler/test_gen/src/gen_primitives.rs:2516]: so this is a regression right? usually an alias analysis error means some inconsistency with the layouts. Any idea what's going on here?

File: crates/compiler/unify/src/fix.rs [hunk 2]
```diff
@@ -0,0 +1,334 @@
...
+                            return Ok(chain);
+                        }
+                    }
+
+                    Err(())
+                }
+                (EmptyRecord, EmptyRecord)
+                | (EmptyTagUnion, EmptyTagUnion) => Err(()),
+                _ => internal_error!(
+                    "structures {:?} and {:?} do not unify; they should never have been involved in fixing!",
```
Comment (folkertdev) [inline crates/compiler/unify/src/fix.rs:305]: is that true? e.g. `EmptyRecord` can unify with a record with zero fields. `FunctionOrTagUnion` also has more unification options than what this pattern match does.

**Review by folkertdev — APPROVED** [review]
two things did not quite make sense to me, but can probably be handled later

**Comment by BrianHicks** [comment]
looks like rbt might be one of the things this doesn't totally solve: https://github.com/roc-lang/rbt/pull/93

Is there a tracking issue where I can stick that?

**Comment by ayazhafiz** [comment]
@BrianHicks could you please cut a small reproduction and file an issue? I’ll take a look this week.

**Comment by BrianHicks** [comment]
I can try! I might not get to it this week (out for US Thanksgiving on Thursday and Friday), but I've got it tracked.

File: crates/compiler/test_gen/src/gen_primitives.rs (hunk 1 above)
Comment (ayazhafiz) [reply crates/compiler/test_gen/src/gen_primitives.rs:2516]: I think we're making it farther than we usually do. My guess is previously this was an error and we stopped generating mono early. Now we go further but the morphic IR is bad

File: crates/compiler/unify/src/fix.rs (hunk 2 above)
Comment (ayazhafiz) [reply crates/compiler/unify/src/fix.rs:305]: You're right, it's not true
