### PR TITLE
Fix parsing lists in tag patterns

### LINKED ISSUE #6074: Parser bug `Expr(When(Arrow(@3298), @3274), @570)`
Runs fine, but crashes with `roc format`
```
roc examples/Tasks/main.roc -- "http://roc-lang.org" roc.html       
Completed
roc format examples/Tasks/main.roc
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Formatting bug; formatted code isn't valid

I wrote the incorrect result to this file for debugging purposes:
examples/Tasks/main.roc-format-failed

Parse error was: "Expr(When(Arrow(@3298), @3274), @570)"

', crates/cli/src/format.rs:101:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
### main.roc-format-failed
```
app "task-usage"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br",
        colors: "https://github.com/lukewilliamboswell/roc-ansi-escapes/releases/download/0.1.1/cPHdNPNh8bjOrlOgfSaGBJDz6VleQwsPdW0LJK6dbGQ.tar.br",
    }
    imports [
        pf.Stdout,
        pf.Stderr,
        pf.Arg,
        pf.Env,
        pf.Http,
        pf.Dir,
        pf.Utc,
        pf.File,
        pf.Path.{ Path },
        pf.Task.{ Task },
        colors.Color,
    ]
    provides [main] to pf

main : Task {} *
main = run |> Task.onErr handleErr

Error : [
    UnableToReadArgs,
    UnableToReadDbgEnv Str,
    UnableToFetchHtml Str,
    UnableToWriteFile Path,
    UnableToReadCwd,
    FileNotWritten Path,
]

handleErr : Error -> Task {} *
handleErr = \err ->
    usage = "DEBUG=1 roc main.roc -- \"http://roc-lang.org\" roc.html"
    msg =
        when err is
            UnableToReadArgs -> "Unable to read command line arguments, usage: \(usage)"
            UnableToReadDbgEnv env -> "Unable to read environment variable \(env), usage: \(usage)"
            UnableToFetchHtml httpErr -> "Unable to fetch URL \(httpErr), usage: \(usage)"
            UnableToWriteFile path -> "Unable to write file \(Path.display path), usage: \(usage)"
            UnableToReadCwd -> "Unable to read current working directory, usage: \(usage)"
            FileNotWritten path -> "File \(Path.display path) was not written to current working directory, usage: \(usage)"

    [Color.fg "ERROR:" Red, msg] |> Str.joinWith " " |> Stderr.line

run : Task {} Error
run =

    # Read UTC epoch
    start <- Utc.now |> Task.await

    # Read an environment variable
    debug <- readDbgEnv "DEBUG" |> Task.await

    # Debug print to stdout
    {} <- printDebug debug "DEBUG variable set to verbose" |> Task.await

    # Read command line arguments
    { url, path } <- readUrlArg |> Task.await

    # Debug print to stdout
    {} <- printDebug debug "Fetching content from \(url)..." |> Task.await

    # Fetch a website using HTTP
    content <- fetchHtml url |> Task.await

    # Debug print to stdout
    {} <- printDebug debug "Saving content to \(Path.display path)..." |> Task.await

    # Write to a file
    {} <-
        File.writeUtf8 path content
        |> Task.onErr \_ -> Task.err (UnableToWriteFile path)
        |> Task.await

    # List the contents of cwd directory
    {} <-
        listCwd
        |> Task.map \paths -> paths |> List.map Path.display |> Str.joinWith ","
        |> Task.await \files -> printDebug debug "Files in current directory: \(files)"
        |> Task.onErr \_ ->
            # TODO remove once https://github.com/roc-lang/basic-cli/pull/136 is released
            # `Dir.list` is currently unimplemented, ignore errors for now
            Task.ok {}
        |> Task.await

    # Read UTC epoch
    end <- Utc.now |> Task.await
    duration = start |> Utc.deltaAsMillis end |> Num.toStr

    # Final task doesn't need to be awaited
    when debug is
        DebugSet -> printDebug debug "Completed in \(duration)ms"
        DebugNotSet -> Stdout.line "Completed"

readUrlArg : Task { url : Str, path : Path } Error
readUrlArg =
    args <- Arg.list |> Task.attempt

    when args is
        Ok [_, first, second, ..] -> Task.ok { url: first, path: Path.fromStr second }
        _ -> Task.err UnableToReadArgs

readDbgEnv : Str -> Task [DebugSet, DebugNotSet] Error
readDbgEnv = \var ->
    result <- Env.var var |> Task.attempt

    when result is
        Ok value if !(Str.isEmpty value) -> Task.ok DebugSet
        _ -> Task.ok DebugNotSet

printDebug : [DebugSet, DebugNotSet], Str -> Task {} Error
printDebug = \debug, msg ->
    when debug is
        DebugSet -> [Color.fg "INFO:" Green, msg] |> Str.joinWith " " |> Stdout.line
        DebugNotSet -> Task.ok {}

fetchHtml : Str -> Task Str Error
fetchHtml = \url ->
    { Http.defaultRequest & url }
    |> Http.send
    |> Task.onErr \err -> Task.err (UnableToFetchHtml (Http.errorToString err))

listCwd : Task (List Path) Error
listCwd =
    Path.fromStr ""
    |> Dir.list
    |> Task.onErr \_ -> Task.err UnableToReadCwd
```

### PR DESCRIPTION
**Pull request by lukewilliamboswell**
Fix #6074

### CODE REVIEW

File: crates/compiler/parse/src/pattern.rs [hunk 1]
```diff
@@ -194,22 +196,6 @@ pub fn loc_implements_parser<'a>() -> impl Parser<'a, Loc<Implements<'a>>, EPatt
     )
 }
 
-fn loc_parse_tag_pattern_arg<'a>() -> impl Parser<'a, Loc<Pattern<'a>>, EPattern<'a>> {
-    one_of!(
-        specialize_err(EPattern::PInParens, loc_pattern_in_parens_help()),
-        loc!(underscore_pattern_help()),
-        // Make sure `Foo Bar 1` is parsed as `Foo (Bar) 1`, and not `Foo (Bar 1)`
```
Comment (joshuawarner32) [inline crates/compiler/parse/src/pattern.rs:201]: Might be useful to move this comment to above, to where we're calling `loc_pattern_help_help(false)`

Comment (lukewilliamboswell) [reply crates/compiler/parse/src/pattern.rs:201]: Good point

**Review by rtfeldman — APPROVED** [review]
