### PR TITLE
Fix #8517

### LINKED ISSUE #8517: Failed `expect` causes a segfault
A segfault results from an `expect` that does not pass:

```ruby
# in test/fx
app [main!] { pf: platform "./platform/main.roc" }

main! = || {
  expect 1 == 2
}
```

Output:

```
error: Child process /Users/felipe.vogel/Library/Caches/roc/b6f30aba45b1df3da823ddda3020fdaf/temp/roc-tmp-Xk8LZHIALa15eutYbtggYxKr0SUvnMuh/roc_run_748818574 killed by signal: 11
error: Child process crashed with segmentation fault (SIGSEGV)
```

If the `expect` passes (e.g. `expect 1 == 1`) then the program runs to completion and there is no output.

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

File: src/base/CommonEnv.zig [hunk 1]
```diff
@@ -57,7 +57,15 @@ pub fn relocate(self: *CommonEnv, offset: isize) void {
...
-    // Note: source is not relocated - it should be set manually
+    // Relocate source slice pointer if it is non-empty.
+    // The underlying bytes live in the same allocation as the rest of the
+    // module data (e.g. shared memory used by the interpreter), so we can
+    // adjust the pointer by the same offset.
+    if (self.source.len > 0) {
+        const old_ptr = @intFromPtr(self.source.ptr);
+        const new_ptr = @as(isize, @intCast(old_ptr)) + offset;
+        self.source.ptr = @ptrFromInt(@as(usize, @intCast(new_ptr)));
+    }
```
Comment (Anton-4) [inline src/base/CommonEnv.zig:67]: @lukewilliamboswell I noticed you wrote the original note, is this change ok?

Comment (lukewilliamboswell) [reply src/base/CommonEnv.zig:67]: Sorry I paged this out of memory a while back ... I'm not sure
