### PR TITLE
#7407: Register package dependent packages

### LINKED ISSUE #7407: Roc docs hangs indefinitely for any package depending on another package
**Description**:  
As the title suggests, `roc docs` hangs indefinitely when processing a package that depends on an external package.  

### Steps to Reproduce:  
1. Use the following files:  

**main.roc**  
```roc
package [Module] {
    ex: "https://github.com/imclerran/roc-ex/releases/download/v0.1.0/t5XMk1-aApXQm_XHaZodFPrc4o5lELIADyAqnYrrCv0.tar.br",
}
```  

**Module.roc**  
```roc
module []
import ex.Example
```  

2. Run `roc docs`.  

### Expected Behavior:  
Documentation generation completes successfully without hanging.  

### Actual Behavior:  
The command hangs indefinitely, making it impossible to generate documentation for packages with dependencies.

### PR DESCRIPTION
**Pull request by gamebox**
A package that depended on another package would hang forever because nothing registered the other package as a module to load like it would with an App.  This fixes that.

Closes #7407

### CODE REVIEW

**Comment by gamebox** [comment]
Cargo test and clippy pass locally

**Comment by smores56** [comment]
Have you tested this with real packages?

File: crates/compiler/load_internal/src/file.rs [hunk 1]
```diff
@@ -1342,7 +1342,31 @@ fn handle_root_type<'a>(
 
                 Ok((header_output, RootType::Module { main_path }))
             }
-            App { .. } | Package { .. } | Platform { .. } => Ok((header_output, RootType::Main)),
+            Package { .. } => {
```
Comment (smores56) [inline crates/compiler/load_internal/src/file.rs:1345]: Seems better to just move this up to the above matched group of modules. Is that not an option?

**Comment by gamebox** [comment]
Depends on what you mean by a real package. I built my own packages and had them depend on others. Do you have examples I should check out?

**Comment by smores56** [comment]
No, that works. I just meant packages instead of a Rust test, which wasn't added. I think if you got this working with your own packages, that gives me confidence that it'll work.

**Comment by gamebox** [comment]
How would I go about adding a test for this?  And where would it live?  load_internal? Work?

File: crates/compiler/load_internal/src/file.rs (hunk 1 above)
Comment (gamebox) [reply crates/compiler/load_internal/src/file.rs:1345]: I can, just need another match to set the root type

Comment (gamebox) [reply crates/compiler/load_internal/src/file.rs]: Done

**Comment by gamebox** [comment]
Added a unit test for you @smores56

File: crates/compiler/load_internal/src/file.rs [hunk 2]
```diff
@@ -1317,8 +1317,13 @@ fn handle_root_type<'a>(
 
         use HeaderType::*;
 
+        let use_main = match header_type {
+            Package { .. } | App { .. } | Platform { .. } => true,
+            Module { .. } | Builtin { .. } | Hosted { .. } => false,
+        };
```
Comment (ayazhafiz) [inline crates/compiler/load_internal/src/file.rs:1323]: maybe localize to the usage site

**Review by ayazhafiz — DISMISSED** [review]

File: crates/compiler/load_internal/src/file.rs (hunk 2 above)
Comment (gamebox) [reply crates/compiler/load_internal/src/file.rs:1323]: Couldn't find a way due to borrow issue without introducing clones

File: crates/compiler/load_internal/tests/test_load.rs [hunk 3]
```diff
@@ -2131,3 +2131,51 @@ fn roc_file_no_extension() {
...
+
+            foo = OtherMod.say "hello"
+            "#
+            ),
+        ),
+        (
+            "other/main.roc",
+            indoc!(
+                r#"
+            package [OtherMod] { other: "other/main.roc" }
```
Comment (smores56) [inline crates/compiler/load_internal/tests/test_load.rs:2162]: This will probably not work in the future since I don't think we want to allow cyclical package dependencies, including the trivial cycle of self dependency. If possible, could you make a third package and have the second depend on it?

**Review by smores56 — APPROVED** [review]
