### PR TITLE
roc dev: report the status code of the child process

### LINKED ISSUE #5428: roc dev ends with exit code 0 on panic
A test with `helloWorldNoURL.roc` where I altered `roc_fx_stdoutLine` in `examples/cli/cli-platform/src/lib.rs` to panic:
```
❯ cargo run --release run examples/helloWorldNoURL.roc
    Finished release [optimized] target(s) in 0.24s
     Running `target/release/roc run examples/helloWorldNoURL.roc`
🔨 Rebuilding platform...
thread 'main' panicked at 'explicit panic', src/lib.rs:310:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) took 18s 
❯ echo $?
134

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) 
❯ cargo run --release dev examples/helloWorldNoURL.roc
    Finished release [optimized] target(s) in 0.18s
     Running `target/release/roc dev examples/helloWorldNoURL.roc`
🔨 Rebuilding platform...
thread 'main' panicked at 'explicit panic', src/lib.rs:310:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) 
❯ echo $?
0
```
It may be relevant that [roc_dev_native](https://github.com/roc-lang/roc/blob/28e56937ccab4da5792fa9779bb3779063a2f9f5/crates/cli/src/lib.rs#L1009) uses `execve` after `libc::fork` vs the "direct" `execve` call in `roc_run_native_fast`.

This incorrect exit code hides certain failures of `cli_run` tests.

Do you know how we could fix this @folkertdev?

### PR DESCRIPTION
**Pull request by folkertdev**
fix #5428

we now report the status code of the child process, which is important if the status code is nonzero (indicating failure)

### CODE REVIEW

**Comment by folkertdev** [comment]
@Anton-4 so we actually get some failures reported now. did you look into those errors already (I'm not sure what prompted the issue https://github.com/roc-lang/roc/issues/5428)

**Comment by Anton-4** [comment]
Thanks @folkertdev :)
I can't find what failure I was analyzing when I posted #5428, btw GPT4 says `unix_wait_status(35584)` is a segfault.

**Comment by Anton-4** [comment]
All the cli_run tests pass now :)
But we do have some segfaults remaining:
```
glue_cli_run::nullable_unwrapped
glue_cli_run::nullable_wrapped
```
I'll do a quick valgrind check tomorrow.

**Comment by Anton-4** [comment]
```
valgrind ./crates/glue/tests/fixtures/nullable-wrapped/app
==708913== Memcheck, a memory error detector
==708913== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==708913== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==708913== Command: ./crates/glue/tests/fixtures/nullable-wrapped/app
==708913== 
tag_union was: StrFingerTree::More("foo", StrFingerTree::More("bar", StrFingerTree::Empty))
`More "small str" (Single "other str")` is: StrFingerTree::More("small str", StrFingerTree::Single("other str"))
`More "small str" Empty` is: StrFingerTree::More("small str", StrFingerTree::Empty)
`Single "small str"` is: StrFingerTree::Single("small str")
`Empty` is: StrFingerTree::Empty
==708913== Can't extend stack to 0x485d138 during signal delivery for thread 1:
==708913==   no stack segment
==708913== 
==708913== Process terminating with default action of signal 11 (SIGSEGV)
==708913==  Access not within mapped region at address 0x485D138
==708913==    at 0x249024: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==    by 0x48D1494: __run_exit_handlers (exit.c:113)
==708913==    by 0x48D160F: exit (exit.c:143)
==708913==    by 0x1D7266: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==    by 0x1: ???
==708913==    by 0x1CC95E: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==  If you believe this happened as a result of a stack
==708913==  overflow in your program's main thread (unlikely but
==708913==  possible), you can try to increase the size of the
==708913==  main thread stack using the --main-stacksize= flag.
==708913==  The main thread stack size used in this run was 8388608.
==708913== 
==708913== HEAP SUMMARY:
==708913==     in use at exit: 600 bytes in 15 blocks
==708913==   total heap usage: 27 allocs, 12 frees, 3,833 bytes allocated
==708913== 
==708913== LEAK SUMMARY:
==708913==    definitely lost: 400 bytes in 10 blocks
==708913==    indirectly lost: 200 bytes in 5 blocks
==708913==      possibly lost: 0 bytes in 0 blocks
==708913==    still reachable: 0 bytes in 0 blocks
==708913==         suppressed: 0 bytes in 0 blocks
==708913== Rerun with --leak-check=full to see details of leaked memory
==708913== 
==708913== For lists of detected and suppressed errors, rerun with: -s
==708913== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by Anton-4** [comment]
[nullable-wrapped-build-folder.zip](https://github.com/roc-lang/roc/files/12870619/nullable-wrapped-build-folder.zip)

**Comment by Anton-4** [comment]
Running with `--debug` did not clear up the `???` in the valgrind output.

**Comment by Anton-4** [comment]
I've ignored the `nullable_unwrapped` and `nullable_wrapped` tests (on linux only). This PR would help us detect newly introduced errors so it seems smart to ignore those tests and get this merged in.

**Review by Anton-4 — APPROVED** [review]

**Comment by ayazhafiz** [comment]
Wait, are we sure that this PR does not cause the glue failures? It is odd to me that it would SIGSEGV on this branch but not elsewhere.

File: crates/cli/src/lib.rs [hunk 1]
```diff
@@ -1100,9 +1106,9 @@ fn roc_dev_native(
                         memory.reset();
                     }
                 }
-            }
+            };
 
-            std::process::exit(0)
+            std::process::exit(exit_code)
```
Comment (Anton-4) [inline crates/cli/src/lib.rs:1111]: @ayazhafiz I double-checked for you:
```
roc on  main [!] is 📦 v0.0.1 via 🦀 v1.71.1 via ❄️  impure (nix-shell-env) took 4s 
❯ ./target/release/roc dev /home/username/gitrepos/roc5/roc/crates/glue/tests/fixtures/nullable-wrapped/app.roc
🔨 Rebuilding platform...
tag_union was: StrFingerTree::More("foo", StrFingerTree::More("bar", StrFingerTree::Empty))
`More "small str" (Single "other str")` is: StrFingerTree::More("small str", StrFingerTree::Single("other str"))
`More "small str" Empty` is: StrFingerTree::More("small str", StrFingerTree::Empty)
`Single "small str"` is: StrFingerTree::Single("small str")
`Empty` is: StrFingerTree::Empty

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.71.1 via ❄️  impure (nix-shell-env) 
❯ echo $?
0

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.71.1 via ❄️  impure (nix-shell-env) 
❯ ./crates/glue/tests/fixtures/nullable-wrapped/app
tag_union was: StrFingerTree::More("foo", StrFingerTree::More("bar", StrFingerTree::Empty))
`More "small str" (Single "other str")` is: StrFingerTree::More("small str", StrFingerTree::Single("other str"))
`More "small str" Empty` is: StrFingerTree::More("small str", StrFingerTree::Empty)
`Single "small str"` is: StrFingerTree::Single("small str")
`Empty` is: StrFingerTree::Empty
Segmentation fault (core dumped)
```
It is segfaulting on main but it's hidden because the output was correct. We used to forget to check the exit code (which indicated the segfault) this PR fixes that.
