### PR TITLE
Dev backend glue primitives

### LINKED ISSUE #6348: Simple dict crashes repl
if i fire up the roc repl and try to make a simple dict, the repl hard crashes.

For example:

```
RUST_BACKTRACE=full roc repl
Dict.single "foo" "bar"
```

```
thread 'main' panicked at 'not yet implemented: low level, NumToFloatCast', crates/compiler/gen_dev/src/lib.rs:1947:18
stack backtrace:
   0:     0x55e78d5316c1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
   1:     0x55e78d55ef8f - core::fmt::write::h6d54cd7c9e155ec5
   2:     0x55e78d52ce21 - std::io::Write::write_fmt::h6a453a71c692f63b
   3:     0x55e78d5314d5 - std::sys_common::backtrace::print::h4ddf81241a51b337
   4:     0x55e78d532b57 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
   5:     0x55e78d532944 - std::panicking::default_hook::h21f14afd59f7aef9
   6:     0x55e78d53300c - std::panicking::rust_panic_with_hook::h45f66047b14c555c
   7:     0x55e78d532f07 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
   8:     0x55e78d531af6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
   9:     0x55e78d532c52 - rust_begin_unwind
  10:     0x55e78a9612e3 - core::panicking::panic_fmt::h54ec9d0e3180a83d
  11:     0x55e78adffbaf - roc_gen_dev::Backend::build_run_low_level::h6c0a584d2573ca12
  12:     0x55e78adfb1d0 - roc_gen_dev::Backend::build_expr::hcdaa47de3ef09ff6
  13:     0x55e78adea13f - roc_gen_dev::Backend::build_stmt::hbc1c4438fe7de63c
  14:     0x55e78ade0d92 - roc_gen_dev::Backend::build_proc::h1ee2c5ff04f5861a
  15:     0x55e78addc2f4 - roc_gen_dev::object_builder::build_proc::hfe93a15acf6ae1cc
  16:     0x55e78add2ffe - roc_gen_dev::object_builder::build_object::hbca21b1e2f719431
  17:     0x55e78adcbd0e - roc_gen_dev::object_builder::build_module::ha6f82da45453f72e
  18:     0x55e78aa6969e - roc_repl_cli::cli_gen::eval_llvm::h0fbc12e16214c4f6
  19:     0x55e78aa71d82 - roc_repl_cli::main::hddcf6b045b5e5cdc
  20:     0x55e78aa484a6 - roc::main::h67a4e2b1b23e752e
  21:     0x55e78aa3cb33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f8a57fd613ad455
  22:     0x55e78aa3cbf3 - std::rt::lang_start::{{closure}}::h100c87f8f4f0a390
  23:     0x55e78d523935 - std::rt::lang_start_internal::hf502095b101390bb
  24:     0x55e78aa497f5 - main
  25:     0x7fa81c63ffce - __libc_start_call_main
  26:     0x7fa81c640089 - __libc_start_main_impl
  27:     0x55e78aa3b935 - _start
  28:                0x0 - <unknown>
  ```
  
  I'm using revision b1f7316fce03f64179ed183498b4daec3b91e546 built/installed via nix.

### PR DESCRIPTION
**Pull request by folkertdev**
fixes #6348

some implementations needed to run glue with the `--dev` flag. That still does not work, so some glue-specific stuff will follow in a later PR.

### CODE REVIEW

File: crates/compiler/gen_dev/src/generic64/storage.rs [hunk 1]
```diff
@@ -448,17 +448,26 @@ impl<
...
+                if base_offset % 8 == 0 && size == 8 {
+                    // The primitive is aligned and the data is exactly 8 bytes, treat it like regular stack.
+                    let reg = self.get_float_reg(buf);
+                    ASM::mov_freg64_base32(buf, reg, base_offset);
+                    self.float_used_regs.push((reg, *sym));
+                    self.symbol_storage_map.insert(*sym, Reg(Float(reg)));
+                    self.free_reference(sym);
+                    reg
+                } else if base_offset % 4 == 0 && size == 4 {
+                    // The primitive is aligned and the data is exactly 8 bytes, treat it like regular stack.
```
Comment (bhansconnect) [inline crates/compiler/gen_dev/src/generic64/storage.rs:461]:
```suggestion
                    // The primitive is aligned and the data is exactly 4 bytes, treat it like regular stack.
```

**Review by bhansconnect — APPROVED** [review]

File: crates/compiler/gen_dev/src/generic64/storage.rs (hunk 1 above)
Comment (folkertdev) [reply crates/compiler/gen_dev/src/generic64/storage.rs:461]: running CI for that seems kind of silly. I'll try and get it into another PR
