### PR TITLE
centralized commands, better errors, link build command refactoring

### LINKED ISSUE #3631: Improve messaging for missing platform dependencies
I don't have clang or Rust or Zig installed in my operating system, so I got the following panic when running an app outside of `nix develop`:
```sh-session
[jan@framey roc]$ nix develop
[jan@framey roc]$ 
[jan@framey roc]$ ./target/release/roc ../project-euler-in-roc/2.roc
🔨 Rebuilding host...
4613732
[jan@framey roc]$
[jan@framey roc]$ exit
exit
[jan@framey roc]$
[jan@framey roc]$ cd ../project-euler-in-roc/
[jan@framey project-euler-in-roc]$
[jan@framey project-euler-in-roc]$ ../roc/target/release/roc 2.roc
🔨 Rebuilding host...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/compiler/build/src/link.rs:360:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', crates/cli/src/build.rs:283:46
[jan@framey project-euler-in-roc]$
[jan@framey project-euler-in-roc]$ ../roc/target/release/roc 2.roc --precompiled-host=true
4613732
[jan@framey project-euler-in-roc]$
```

### LINKED ISSUE #4423: make centralized `zig_cmd` function in `crates/utils`
Currently we use `std::process::Command` in several places to invoke zig. Using a single function would help us track the usage of zig in the codebase and would allow us to add arguments to every zig call.

### PR DESCRIPTION
**Pull request by Anton-4**
- Closes #4423: centralized commands for cargo, zig, and clang.
- Closes #3631: nice error messages for when rust, zig, or clang is not installed.
- Refactoring of `validate_output`; error messages now print the entire command with all arguments.

### CODE REVIEW

File: crates/compiler/build/src/link.rs [hunk 1]
```diff
@@ -113,9 +107,9 @@ pub fn build_zig_host_native(
     target: &str,
     opt_level: OptLevel,
     shared_lib_path: Option<&Path>,
-) -> Output {
-    let mut command = Command::new(&zig_executable());
-    command
+) -> Command {
+    let mut zig_cmd = zig();
+    zig_cmd
```
Comment (Anton-4) [inline crates/compiler/build/src/link.rs:112]: I renamed this to `zig_cmd` because it is more descriptive than `command`.

File: crates/compiler/build/src/link.rs [hunk 2]
```diff
@@ -160,24 +154,24 @@ pub fn build_zig_host_native(
...
     if matches!(opt_level, OptLevel::Optimize) {
-        command.args(&["-O", "ReleaseSafe"]);
+        zig_cmd.args(&["-O", "ReleaseSafe"]);
     } else if matches!(opt_level, OptLevel::Size) {
-        command.args(&["-O", "ReleaseSmall"]);
+        zig_cmd.args(&["-O", "ReleaseSmall"]);
     }
 
-    command.output().unwrap()
+    zig_cmd
```
Comment (Anton-4) [inline crates/compiler/build/src/link.rs:174]: Returning the `Command` instead of the `Output` allows for more code re-use and better error message where the entire command with all args is printed.

File: crates/compiler/build/src/link.rs [hunk 3]
```diff
@@ -684,23 +676,22 @@ pub fn rebuild_host(
...
+                "-r",
+                "-L",
+                cargo_out_dir.to_str().unwrap(),
+                c_host_dest.to_str().unwrap(),
+                "-lhost",
+                "-o",
+                host_dest.to_str().unwrap(),
+            ]);
+
+            run_build_command(ld_cmd, "c_host.o");
```
Comment (Anton-4) [inline crates/compiler/build/src/link.rs:694]: `ld_cmd` needs to be initialized separately first to prevent ownership issues.

File: crates/cli_utils/Cargo.toml [hunk 4]
```diff
@@ -14,6 +14,7 @@ roc_collections = { path = "../compiler/collections" }
 roc_reporting = { path = "../reporting" }
 roc_load = { path = "../compiler/load" }
 roc_module = { path = "../compiler/module" }
+roc_utils = { path = "../utils" }
```
Comment (Anton-4) [inline crates/cli_utils/Cargo.toml:17]: The centralized commands `cargo()`, `zig()` and `clang()` were put in `roc_utils`.

**Review by folkertdev — APPROVED** [review]
Nice, much nicer errors in a bunch of cases!
