### PR TITLE
Freshly instantiate nested recursion variables under aliases and opaques

### LINKED ISSUE #5264: roc build panics with Invalid InsertValueInst operands when importing an interface
This is similar to my previous issue #5212 that was fixed, but I find I only get this error when I import LinkedList from another file. Putting all the definitions in a single file compiles and run successfully. Using MacOS 13.1 with Intel CPU, `roc_nightly-macos_x86_64-2023-04-08-3b28e89`.

`main.roc`:

```
app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.1/97mY3sUwo433-pcnEQUlMhn-sWiIf_J9bPhcAFZoqY4.tar.br" }
    imports [pf.Stdout, LinkedList.{ LinkedList }]
    provides [main] to pf

main = 
    list = LinkedList.single "foo"
    newlist = LinkedList.push list "bar"
    Stdout.line (Num.toStr (LinkedList.len newlist))
```

`LinkedList.roc`:

```
interface LinkedList
    exposes [
        LinkedList,
        single,
        push,
        pop,
        toList,
        concat,
        walk,
        empty,
        len,
    ]
    imports []

LinkedList a := LL a

LL a : [Nil, Cons { first : a, rest : LL a, length : Nat }]

empty : {} -> LinkedList a
empty = \{} -> @LinkedList Nil

len : LinkedList a -> Nat
len = \@LinkedList list ->
    when list is
        Nil -> 0
        Cons { length } -> length

single : a -> LinkedList a
single = \item -> @LinkedList (Cons { first: item, rest: Nil, length: 1 })

push : LinkedList a, a -> LinkedList a
push = \@LinkedList list, item -> @LinkedList (Cons { first: item, rest: list, length: (len (@LinkedList list)) + 1 })

pop : LinkedList a -> [Cons { first : a, rest : LinkedList a }, Nil]
pop = \@LinkedList list ->
    when list is
        Nil -> Nil
        Cons { first, rest } -> Cons { first, rest: @LinkedList rest }

toList : LinkedList a -> List a
toList = \list ->
    (T out _) = walk list (T (List.withCapacity (len list)) 0) \T state index, elem ->
        T (List.set state index elem) (index + 1)
    out

concat : LinkedList a, LinkedList a -> LinkedList a
concat = \@LinkedList list1, @LinkedList list2 ->
    concatenated =
        when list1 is
            Nil -> list2
            Cons { first, rest, length } ->
                Cons {
                    first: first,
                    rest: concat (@LinkedList rest) (@LinkedList list2),
                    length: (len (@LinkedList list2)) + length,
                }
    @LinkedList concatenated

walk : LinkedList elem, state, (state, elem -> state) -> state
walk = \@LinkedList list, state, fn ->
    when list is
        Nil -> state
        Cons { first, rest } -> walk (@LinkedList rest) (fn state first) fn
```

Running `roc build` gives:

```
Invalid InsertValueInst operands!
  %insert_record_field3 = insertvalue { { %str.RocStr, i64, { [0 x i64], [16 x i8] }* } } zeroinitializer, { %str.RocStr, i64, { [0 x i64], [40 x i8] }* } %insert_record_field2, 0, !dbg !1795


Function "LinkedList_single_beb22fad19423347b2aa99b33212e862ded3f83df5d6238acb1a6a9ade3e" failed LLVM verification in NON-OPTIMIZED build. Its content was:

define internal fastcc { [0 x i64], [40 x i8] }* @LinkedList_single_beb22fad19423347b2aa99b33212e862ded3f83df5d6238acb1a6a9ade3e(%str.RocStr* %item) !dbg !1794 {
entry:
  %load_tag_to_put_in_struct = load %str.RocStr, %str.RocStr* %item, align 8, !dbg !1795
  %insert_record_field = insertvalue { %str.RocStr, i64, { [0 x i64], [40 x i8] }* } zeroinitializer, %str.RocStr %load_tag_to_put_in_struct, 0, !dbg !1795
  %insert_record_field1 = insertvalue { %str.RocStr, i64, { [0 x i64], [40 x i8] }* } %insert_record_field, i64 1, 1, !dbg !1795
  %insert_record_field2 = insertvalue { %str.RocStr, i64, { [0 x i64], [40 x i8] }* } %insert_record_field1, { [0 x i64], [40 x i8] }* null, 2, !dbg !1795
  %call_builtin = call i8* @roc_builtins.utils.allocate_with_refcount(i64 40, i32 8), !dbg !1795
  %alloc_cast_to_desired = bitcast i8* %call_builtin to { [0 x i64], [40 x i8] }*, !dbg !1795
  %insert_record_field3 = insertvalue { { %str.RocStr, i64, { [0 x i64], [16 x i8] }* } } zeroinitializer, { %str.RocStr, i64, { [0 x i64], [40 x i8] }* } %insert_record_field2, 0, !dbg !1795
  %tag_alloca = alloca { [0 x i64], [40 x i8] }, align 8, !dbg !1795
  %data_buffer = getelementptr inbounds { [0 x i64], [40 x i8] }, { [0 x i64], [40 x i8] }* %tag_alloca, i32 0, i32 1, !dbg !1795
  %to_data_ptr = bitcast [40 x i8]* %data_buffer to { { %str.RocStr, i64, { [0 x i64], [16 x i8] }* } }*, !dbg !1795
  store { { %str.RocStr, i64, { [0 x i64], [16 x i8] }* } } %insert_record_field3, { { %str.RocStr, i64, { [0 x i64], [16 x i8] }* } }* %to_data_ptr, align 8, !dbg !1795
  %load_tag = load { [0 x i64], [40 x i8] }, { [0 x i64], [40 x i8] }* %tag_alloca, align 8, !dbg !1795
  store { [0 x i64], [40 x i8] } %load_tag, { [0 x i64], [40 x i8] }* %alloc_cast_to_desired, align 8, !dbg !1795
  ret { [0 x i64], [40 x i8] }* %alloc_cast_to_desired, !dbg !1795
}
thread 'main' panicked at '😱 LLVM errors when defining function "LinkedList_single_beb22fad19423347b2aa99b33212e862ded3f83df5d6238acb1a6a9ade3e"; I wrote the full LLVM IR to "main.ll"', crates/compiler/gen_llvm/src/llvm/build.rs:4871:21
```

### PR DESCRIPTION
**Pull request by ayazhafiz**
Like we instantiate nested lambda set variables and nested OIOP
variables for aliases, we need to do the same for recursion variables.

Closes #5264

### CODE REVIEW

File: crates/compiler/types/src/types.rs [hunk 1]
```diff
@@ -3281,6 +2925,208 @@ impl Type {
...
+{
+    use Type::*;
+
+    match typ {
+        Function(args, closure, ret) => {
+            for arg in args {
+                instantiate_aliases(arg, region, aliases, ctx);
+            }
+            instantiate_aliases(closure, region, aliases, ctx);
+            instantiate_aliases(ret, region, aliases, ctx);
```
Comment (folkertdev) [inline crates/compiler/types/src/types.rs:2951]: it looks like this could be written using an explicit stack, would that not be better? it depends a bit on when this is used (e.g. user-defined types are likely quite small, but internal ones can grow pretty big)

**Review by folkertdev — APPROVED** [review]

File: crates/compiler/types/src/types.rs (hunk 1 above)
Comment (ayazhafiz) [reply crates/compiler/types/src/types.rs:2951]: yes, that's a good idea, let's do it in a follow-up.
